name: ETL Pipeline

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:      # Allow manual runs

jobs:
  etl:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install packages
      run: pip install -r requirements.txt
    
    - name: Run ETL
      run: |
        python extract.py
        python transform.py
        python load.py
    
    - name: Run tests
      run: python tests.py
    
    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: final_data.csv